### ISSUE TITLE
Guides should show relative distance

### ISSUE THREAD

**Issue by argyleink** [GoogleChromeLabs/ProjectVisBug#109]
select 1 element, then while hovering on any other, see the distance

**Comment by BlitZz96** [comment]
Was just about to submit an issue regarding this. This would be the cherry on top for me 😍 

Something like this I suppose?
![image](https://i.imgur.com/rMXsGNj.png)

Anyways, really great extension!

**Comment by CyberAP** [comment]
It would also be super cool to measure distance between actual pixels, instead of element dimensions.
For example: in text, ignore the line height and calculate the distance from the actual letter' pixels, the same as it's done in Photoshop.

![image](https://user-images.githubusercontent.com/1462706/48426564-19d0b480-e778-11e8-85f2-4a074f8a75d4.png)

**Comment by squire225** [comment]
It would be good select an element and hover over another, but I would play with the possibility of using the shift or alt key to invoke this feature. Often there are numerous elements on screen and it can help to be able to select a ‘target element’ in which to get the relative distance between.

**Comment by argyleink** [comment]
i like this extension's behavior/features too http://felixniklas.com/dimensions/

**Comment by argyleink** [comment]
shows when **holding alt/opt**
i already like it

![distance-right](https://user-images.githubusercontent.com/1134620/50754583-0b989500-120b-11e9-8b50-28303f8f33a6.gif)

have more states/sides to represent, but wanted to share the 1st iteration cuz it's fun. here's some designs i made to help me think about what I needed to code https://www.figma.com/file/OPpDjc7RTCjR7H84ij5FEClC/Relative-Distance?node-id=1%3A5

**Comment by BlitZz96** [comment]
Awesome! Great job. 🎉

**Comment by argyleink** [comment]
updated styles and have all sides working

![distance-v2](https://user-images.githubusercontent.com/1134620/50799088-8c00d980-128f-11e9-9f51-06939e4d17bc.gif)

**Comment by argyleink** [comment]
released!
