### ISSUE TITLE
Tool Palette should be moveable

### ISSUE THREAD

**Issue by argyleink** [GoogleChromeLabs/ProjectVisBug#114]
Draggable probably, but maybe just pin to left or right

**Comment by profmikegreene** [comment]
Alternatively, you could add a margin to body/html to make the page appear as if it was on an artboard and leave the tool palette fixed to the left. 

I'm not sure I like that better than what you've proposed, but it's a hack I'm using on my pages that have a lot of important UI underneath the palette.

**Comment by argyleink** [comment]
that idea has been on my mind a lot lately, especially if it was combined with #127, we would literally be creating the illusion that the page has become an artboard. hold space bar, pan around, zoom, etc. would be so sweeeeet!

**Comment by argyleink** [comment]
seems like it would need lots of testing though, and that certain sites may fight it pretty hard..

**Comment by argyleink** [comment]
much of this feature request is pacified for me by the ability to hide it (see #202), but i empathize and want the full feature. just wanted to share that hiding it can get it out of the way while you work, and then just bring it back if you need to change to another tool visually (without the keyboard shortcut)
