### ISSUE TITLE
holding shift and clicking something already selected should unselect the clicked element

### ISSUE THREAD

**Issue by argyleink** [GoogleChromeLabs/ProjectVisBug#167]

**Comment by rehat101** [comment]
I have been trying to solve this by checking if the target element exists inside `selected` and if it does then removing it from `selected, labels, handles` array and then removing label and handle DOM elements.

this work nicely for the last element cause the data-id increments and decrements sequentially. However, when I try to unselect an element in the middle, I see issues. 

I'm not sure if this can be an observer not updating the ids? I do get an error when observer tries to `label.update`

**Comment by argyleink** [comment]
went lookin for a published branch of yours to peep, didnt see it. want to share and i'll take a look?

**Comment by rehat101** [comment]
i will share if I have something solid :) what would be an ideal way to unselect a selected element?

**Comment by argyleink** [comment]
from a ux perspective or from the code's perspective?

**Comment by rehat101** [comment]
code's perspective: when elements are selected it gets pushed to the selected array and label gets created inside the labels array, and handles. I saw the `unselect_all` function where you reset the arrays but in this case you want to remove a duplicate element in the arrays...

**Comment by argyleink** [comment]
when an element is selected, the labels and handles are connected to the element with a data-label-id. you should be able to leverage that attribute and it's value to remove the handle, label and attributes from the element and DOM. 

so some pseudo code may look like:
1. if element clicked and already selected
2. grab it's label-id
3. iterate over the selected, handles, and labels arrays to find the matching nodes with the label-id
4. remove the handles and labels from the dom
5. remove the handles and labels from the array
6. remove any visbug data attributes from the source element's attributes
7. remove the source element from the selected array

i'd tuck all this away into a function called unselect() which takes a label-id as a parameter. lemme know how close i was to the final impl!

**Comment by rehat101** [comment]
yes, close but if you see label ids get generated again so there are duplicates. Perhaps, I'm not removing the elements from arrays right?

**Comment by argyleink** [comment]
i got it working with the code in my above commit. want to give it a try and see if it's got the ux expected and didnt break any tools? 
was tellWatchers() what you were missing maybe? 
i ended up leaving the handles and labels in the array, they'd be cleared out soon. but i did want to clear the selected array because some tools register listeners for that array, so it can't have junk in it.

**Comment by rehat101** [comment]
Yep, works.

I believe it was the if/else condition on click -  It increments the label ids sequentially now `tellWatchers()` - what does this do? 

Starting a PR for this

**Comment by argyleink** [comment]
tellWatchers() invokes any registered callbacks with the updated array of selected nodes. some tools use this array and callback method for their functions. I need to document the 2 and or just pick 1. Fine for now though.
