### ISSUE TITLE
Resize

### ISSUE THREAD

**Issue by argyleink** [GoogleChromeLabs/ProjectVisBug#17]
height/width/intrinsic/extrinsic

**Comment by argyleink** [comment]
https://youtu.be/Q2jzq_2Spds?t=28

**Comment by argyleink** [comment]
Spent 5 minutes trying out `resize` and i think with a few ux tweaks it could be super viable. need to try it out more, make a branch and give it a shot. 
- remove `transition: all` while dragging
- remove hover listeners while dragging

https://www.w3schools.com/cssref/css3_pr_resize.asp

![resize](https://user-images.githubusercontent.com/1134620/74390110-20077380-4db5-11ea-8ecd-1a252440b725.gif)

**Comment by mayank99** [comment]
Hey Adam! Did you ever get around to playing with this a bit more? Would love to try my hand at this if you can point me in the right direction. 🤓

**Comment by argyleink** [comment]
I didnt no, though I think about it often!

Here's some leads to help you kick it off:
- selected elements are given the `[data-selected="true"]` attribute and could have the resize styles added to [here](https://github.com/GoogleChromeLabs/ProjectVisBug/blob/main/app/components/vis-bug/vis-bug.css#L6)
- here's [where selected elements are given that attribute](https://github.com/GoogleChromeLabs/ProjectVisBug/blob/main/app/features/selectable.js#L430)
- here's where [hover guards](https://github.com/GoogleChromeLabs/ProjectVisBug/blob/main/app/features/selectable.js#L392) are, so elements bind the cursor dont highlight while resizing 
- could add a mousedown or pointerdown event [listener here](https://github.com/GoogleChromeLabs/ProjectVisBug/blob/main/app/features/selectable.js#L36) to try and infer if the element is being resized?
- adding `overflow: hidden` is a bummer, it'll probably have side effects in some ways. the betters solution is likely to put events on the handle dots of the [pink bounding box](https://github.com/GoogleChromeLabs/ProjectVisBug/blob/main/app/components/selection/handles.element.js). then we could lock the axis they're dragging, complete the visual cues (like those circles look like handles already..), and ultimately give the design like experience instead of the `resize: both` experience. 

lemme know how serious you are in doing this! i could video chat with you, walk you through a few things, and help you along 🙂

**Comment by mayank99** [comment]
Thanks for the response! The code actually looks much more than approachable than I was expecting 👀 and I agree custom events would be better than `resize`.

I'm down for a chat some time in the next few days. What would be the best place to reach out?

**Comment by EllyLoel** [comment]
This may be user error but when trying to resize elements nothing seems to happen. I've tried with different tools (position, measure, etc.), I've tried both in the playground and with the extension, and I've also tried in different browsers. Oh and I also tried with an external mouse and the built in trackpad on my MacBook.

![A screen capture demonstrating the VisBug resize feature not working](https://user-images.githubusercontent.com/63755046/215678406-370a9e18-8c14-4143-8805-0ccf7aa036b9.gif)

**Comment by mayank99** [comment]
@EllyLoel You're right, it's not working for me either 😕 must be a recent regression because I remember using it fairly recently.

**Comment by argyleink** [comment]
hm, thanks for logging the error! a recent build went out with a new plugin, and the build was uploaded by a github action (which was broken for a bit while an api shifted around). maybe something around that happened?

looking at the console:
```js
const handlesEl = e.path.find(el => el.tagName === 'VISBUG-HANDLES')
// e.path is undefined, so find can't be called/found
```

i'll check more later, but that's what i can see now.

**Comment by argyleink** [comment]
fixed it, built deploying
