### ISSUE TITLE
Visbug doesn't launch with local static files

### ISSUE THREAD

**Issue by jadiaz** [GoogleChromeLabs/ProjectVisBug#245]
Using chrome, when I open a static HTML file from the file system `file://test.html` I am unable to launch VisBug. Seems like files served from web server are the only ones that work.

**Comment by argyleink** [comment]
hm, any errors in the console or anything?

i'm able to use the extension on `file://`

![screen shot 2018-12-03 at 10 02 02 pm](https://user-images.githubusercontent.com/1134620/49422070-2dec4e00-f747-11e8-935d-99f2b068273d.png)

**Comment by jadiaz** [comment]
No errors on console. I create a brand new test.html file with only a `div` and `p` tag. Visbug still doesn't launch.

`file:///Users/racan/Downloads/test.html`

Chrome version: Version 70.0.3538.110 (Official Build) (64-bit)
VisBug Chrome plugin version 0.1.16
Mac OS: 10.13.6 (17G3025)

<img width="1697" alt="screen shot 2018-12-04 at 8 37 22 am" src="https://user-images.githubusercontent.com/133032/49453184-df1ed280-f79f-11e8-8fac-94a829be444f.png">

<img width="1684" alt="screen shot 2018-12-04 at 8 38 58 am" src="https://user-images.githubusercontent.com/133032/49453297-18574280-f7a0-11e8-85c3-0ef96c53e7e2.png">

**Comment by argyleink** [comment]
interesting! i can't repro tho!
by chance, did it work once and then never again? or just never once?

**Comment by argyleink** [comment]
repro on linux! still can't repro on mac tho!

**Comment by jadiaz** [comment]
> interesting! i can't repro tho!
> by chance, did it work once and then never again? or just never once?

never once

**Comment by jadiaz** [comment]
> repro on linux! still can't repro on mac tho!

could it be a filesystem issue? I've got my hard drive **APFS Volume • APFS (Encrypted)** configured.

**Comment by argyleink** [comment]
unsure. it looks like chrome is just not launching the extension when pressed. may be out of visbug's control

**Comment by argyleink** [comment]
turns out this is normal published extension behavior

**Comment by A-4-Atom** [comment]
Search for 'live server' on visualStudio Extensions, and use that to open the html file then you will be able to use visbug.

**Comment by MaadhavKrishna** [comment]
It helped me too
