### ISSUE TITLE
Hide hover dashed borders while grid tool is active

### ISSUE THREAD

**Issue by argyleink** [GoogleChromeLabs/ProjectVisBug#258]
![screen shot 2018-12-11 at 8 51 24 pm](https://user-images.githubusercontent.com/1134620/49847738-8b574f00-fd86-11e8-9f4c-702849c67d0b.png)

**Comment by MaximKazionov** [comment]
Hello, can I be assigned to this task?

**Comment by argyleink** [comment]
yep! but the github ui won't let me assign you.. ping me on gitter if you want to chat about your strategy to fix this one 👍
