### ISSUE TITLE
How can I see my local CSS changes?

### ISSUE THREAD

**Issue by jaminroe** [GoogleChromeLabs/ProjectVisBug#296]
How can I view the local changes I've made, so it shows it to me in a CSS rules format? For now, I don't see much value in this extension if you can't easily share/see those changes listed out.

For comparison, check out StyleURL extension. They do this in a very nice, easy to use way — https://www.styleurl.app

**Comment by argyleink** [comment]
you can certainly view the changes you've made! after you've made changes, hover over the elements with the style inspector and it lists your changes at the bottom of the card. for additional sharing and for copying values out, hold `opt/alt` and `click` to pin the card. once a card is pinned, you can copy styles out or screenshot for bug ticket creation. 

![1_oflcylisiyfi3_v8_02jrg](https://user-images.githubusercontent.com/1134620/53253678-b0b1e480-3676-11e9-8345-967696058746.gif)

**Comment by jaminroe** [comment]
Got it thanks! I saw your previous comment too. Thank you!
