### ISSUE TITLE
Ability to move the UI:Visbug tool around on the screen

### ISSUE THREAD

**Issue by tonypius** [GoogleChromeLabs/ProjectVisBug#320]
Is there a way to move the UI of the Visbug tool around on the screen ?

**Comment by mirkea** [comment]
+1
What happens if you're testing a mobile layout and you're trying to check alignment to the left of the screen. The bar got in the way for me in a real world scenario. At least there should be the option to move it to the right side

**Comment by argyleink** [comment]
you can currently hide the toolbar with a hotkey (aka toggle toolbar visibility), which pacifies most needs to move it. hit `cmd+.` or `cmd+/`

also though, i do think being able to move visbug around is valuable, since that matches the behavior of toolbars in most design apps.

**Comment by medeirosjoaquim** [comment]
It would be a great feature and would improve a lot the experience. I see it as a growth opportunity to the ProjectVisBug developers.

**Comment by argyleink** [comment]
fixed with #114 👍
