### ISSUE TITLE
search ux: once a search is completed the input field can't be focused

### ISSUE THREAD

**Issue by argyleink** [GoogleChromeLabs/ProjectVisBug#340]
it's a conflict with the toolbar drag feature

repro:
- click the search icon
- pick a plugin from the dropdown
- try and click back into the search field

**Comment by fxnoob** [comment]
https://github.com/GoogleChromeLabs/ProjectVisBug/blob/6ebfd1a3637ce8fe497bc2e3bb825370c51761c2/app/components/vis-bug/vis-bug.element.js#L97

Reinitializing selected tool on click every time.
So by commenting out this line?
