### ISSUE TITLE
Shortcut for toggling show/hide

### ISSUE THREAD

**Issue by akshitkrnagpal** [GoogleChromeLabs/ProjectVisBug#356]
This is kinda a feature request.

It would be great if there is a shortcut to show/hide.

**Comment by argyleink** [comment]
there is! =) `cmd/ctrl+/` will toggle it visually (while keeping it active), or you can use the extension shortcut to toggle VisBug entirely with `opt/alt+shift+D`
 
here's a list of keyboard commands 👍  https://github.com/GoogleChromeLabs/ProjectVisBug/wiki/Keyboard-Master-List
