### ISSUE TITLE
Edit text fails after editing a container

### ISSUE THREAD

**Issue by phistuck** [GoogleChromeLabs/ProjectVisBug#358]
1. Go to https://github.com/GoogleChromeLabs/ProjectVisBug
2. Double click on the area just above the "License" heading, so it selects the container of most of the readme (screenshot below).
3. Try to double click on the last bullet before "License".

Expected -
Editing that text.
Actual -
You cannot edit stuff anymore.

Going to another tab and back fixes the issue and also due to the outline, I guess this is a `focus` or `tabindex` issue.

![image](https://user-images.githubusercontent.com/184400/61351076-56f2c680-a872-11e9-98a3-423455581d18.png)

**Comment by argyleink** [comment]
`contenteditable` is a bit finicky sometimes. i was able to edit text on that page by double clicking again and being very specific about double clicking on a highlighted node that i wish to edit. space between nodes sets editable on the parent, which `contenteditable` will be finicky about. try to edit specific nodes, as opposed to trying to put an edit mode on a whole chunk. 

agree this is a UX issue, but perhaps the real issue should be logged against the browser's implementation of `contenteditable`..
