### ISSUE TITLE
show some flexbox labels

### ISSUE THREAD

**Issue by argyleink** [GoogleChromeLabs/ProjectVisBug#36]
at least indicate if it's a flex container

**Comment by pewstiepoll** [comment]
Hi @argyleink,
I would really like to contribute to the VisBug project! Mind if I try to help with this one?

**Comment by argyleink** [comment]
yay, do it 👍 

i imagined using [this component](https://github.com/GoogleChromeLabs/ProjectVisBug/blob/master/app/components/selection/label.element.js), which is used [like this](https://github.com/GoogleChromeLabs/ProjectVisBug/blob/master/app/features/selectable.js#L580). 

You'll also want to update the flexbox tools strategy for getting the currently selected items, right now it's lazy, and you'll want proactive in order to display a label on selection. You can steal that work from [here](https://github.com/GoogleChromeLabs/ProjectVisBug/compare/flexbox-fixes#diff-88b451edc4b310ebe463e8febeb48b40R14). 

**pr will tell a story like:**
- while flexbox tool is active
- when user makes a selection, align tool looks at the container(s) and determines if they're flex containers or not
- if a flex container is found, create a label

**maybe some tests to write or def things to be aware of while testing manually:**
- [ ] ensure label position stays during edits
- [ ] ensure label is removed when the tool is switched or nodes are removed/moved

ping again if you need anything!

**Comment by pewstiepoll** [comment]
@argyleink please checkout the PR here: https://github.com/GoogleChromeLabs/ProjectVisBug/pull/374

**Comment by adhrinae** [comment]
Ooops I was trying to make a PR but too late for this 😂

**Comment by argyleink** [comment]
fixed by #374

**Comment by adhrinae** [comment]
is there a reason why this issue reopened?

**Comment by argyleink** [comment]
yeah, the PR merged that resolved this ticket was reverted due to it breaking margin/padding tools. so the task is back open, or just pending a resolution to the PR bug!

**Comment by adhrinae** [comment]
Ah, I've just read the PR again and figured out what happened. My bad.

**Comment by argyleink** [comment]
fixed by #523
