### ISSUE TITLE
Align tool: wrap / nowrap / reverse / forward

### ISSUE THREAD

**Issue by argyleink** [GoogleChromeLabs/ProjectVisBug#370]
Would be great to reverse and wrap. curious what hotkeys we could do or visual buttons we could show? thoughts?

**Comment by lavyda** [comment]
Hi @argyleink 
I would like to contribute to this project. Can I take this issue?

My thoughts on hotkeys:
We can make ctrl + left or right to cycle through properties or we can make individual hotkeys for each property, e.g. shift + w for wrap etc..  
What do you think?

**Comment by argyleink** [comment]
Hi! you can definitely take this issue 👍 

Here's the current hotkey set to help us ideate:
![Screen Shot 2019-09-26 at 1 00 07 PM](https://user-images.githubusercontent.com/1134620/65720892-c862a880-e05d-11e9-884b-d756506a99aa.png)

we have 4 actions to map, split into 2 groups of similar behavior (wrap/order)
could we map them to `cmd/ctrl + shift`, then have up/down be order and left/right be wrap?
- `cmd+shift+up`: nowrap
- `cmd+shift+down`: wrap
- `cmd+shift+left`: reverse
- `cmd+shift+right`: forwards

up/down change wrapping on the container
left/right change order

thoughts?

**Comment by lavyda** [comment]
Sounds good, I like the idea of splitting them.

**Comment by argyleink** [comment]
Rad 🤘 

Here's the steps I'd take (please ask clarifying questions if you need):
- add new `${metaKey}+shift` listeners to the [command_events](https://github.com/GoogleChromeLabs/ProjectVisBug/blob/master/app/features/flex.js#L11) for the arrows you want to get events for
- use [this switch area](https://github.com/GoogleChromeLabs/ProjectVisBug/blob/master/app/features/flex.js#L38) to identify and direct the event
- write `changeOrder` and `changeWrap` functions
- follow patterns made by the `changeDirection` [function ](https://github.com/GoogleChromeLabs/ProjectVisBug/blob/master/app/features/flex.js#L66)
- update [the instruction card](https://github.com/GoogleChromeLabs/ProjectVisBug/blob/master/app/components/vis-bug/model.js#L142) for the flex tool
- update the [flex keyboard trainer component](https://github.com/GoogleChromeLabs/ProjectVisBug/blob/master/app/components/hotkey-map/align.element.js#L32) to display the results of the new keyboard commands
- QA QA QA
- Make a PR
- [append tests](https://github.com/GoogleChromeLabs/ProjectVisBug/blob/master/app/features/flex.test.js) for your feature? (optional but super welcome)

**Comment by lavyda** [comment]
Thanks for the guidance :blush: Since I'm newbie I'll probably have lots of questions :sweat_smile: Anyway I'll start working on it and see how it goes.

**Comment by argyleink** [comment]
fixed in #394
