### ISSUE TITLE
Inspect tool is not scaling properly.

### ISSUE THREAD

**Issue by JoelEinbinder** [GoogleChromeLabs/ProjectVisBug#383]
The inspect tool gets cut off when I try to use it. It looks like its too big for its content window.

Windows 10, Chrome Dev, DPR: 1. Happens on every URL that I tried.
![image](https://user-images.githubusercontent.com/4624233/64737160-1180fd00-d4a1-11e9-8c7f-91f091a979dd.png)

**Comment by argyleink** [comment]
that looks like a backdrop filter render bug! i've seen it in canary, but not in any production builds. you're in a dev build now? can you test stable?

**Comment by JoelEinbinder** [comment]
Suspecting https://chromium.googlesource.com/chromium/src/+/2a63110a9e2b7df6b1411214180fe77611efd0ea

**Comment by argyleink** [comment]
set to be fixed in m78

**Comment by argyleink** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1003415#c13
