### ISSUE TITLE
Using ctrl (meta key) in Trainer on Windows doesn't work properly on some tools

### ISSUE THREAD

**Issue by lavyda** [GoogleChromeLabs/ProjectVisBug#391]
Affected tools: Align, Hue, Font
Happens when using Trainer with hotkey combination that includes ctrl (not just only ctrl). In such cases ctrl is ignored and hints don't update correctly.

How to reproduce (example for Align):
1. Use Align tool
2. Use ctrl + arrowRight to change direction.

Expected behavior:
_align as **row**_ should change to _align as **column**_. What actually happens is that text for alignment is changed instead.

Possible fix:
Instead of [getting meta key](https://github.com/GoogleChromeLabs/ProjectVisBug/blob/master/app/components/hotkey-map/align.element.js#L32) as _hotkeys.cmd_ use _hotkeys[metaKey]_

**Comment by argyleink** [comment]
nice find, thanks!

**Comment by lavyda** [comment]
Maybe I can try to fix it as well? 😄

**Comment by argyleink** [comment]
that'd be lovely!
i'll be much more active in january 2020, thanks for checkin in. let me know if you need any help 👍

**Comment by lavyda** [comment]
Nice 👍 
Regarding meta key. This is probably wrong place to discuss it but I'm not sure what to do. When I ran tests now on Mac I realised that I introduced a bug here e84a335 😞 when I [used 'Control' in tests](https://github.com/GoogleChromeLabs/ProjectVisBug/commit/e84a335732607b016a6260d5a64945b34d511ea5#diff-3e0a04794781f970401ed0d7f1749637R124) It's just that on Mac it should be 'Meta' that's why I didn't have problem on Windows and Travis build passed. Should I make new issue or what to do? Thanks 😄

**Comment by argyleink** [comment]
i think it's fair to add a new issue and resolve it with a different PR. it'll help it get merged faster since it wont be attached to anything else. so just so i'm following properly, you'll be opening up a new issue because some tests are failing on mac? the PR you create to resolve will update places in the tests referencing "control"? sounds straight forward and great!
