### ISSUE TITLE
VisBug doesn't work with local static files 

### ISSUE THREAD

**Issue by KIDevs** [GoogleChromeLabs/ProjectVisBug#406]
Using chrome, when I open a static HTML file from the file system file://test.html** I am unable to launch VisBug. Seems like files served from web server are the only ones that work.

You need to fix the manifest file and js to work correctly offline.

![Kv4FvV4](https://user-images.githubusercontent.com/28823923/68385567-214c5300-016b-11ea-9069-0d32a725d58c.png)

**Comment by argyleink** [comment]
this is a common gotcha with extensions, see here https://github.com/GoogleChromeLabs/ProjectVisBug/issues/245#issuecomment-455837499
