### ISSUE TITLE
Style Manager, Layers, Export/Import code, CSS/JS/HTML Editor, etc

### ISSUE THREAD

**Issue by KIDevs** [GoogleChromeLabs/ProjectVisBug#407]
There is an excellent open source sites page builder.
Github: https://github.com/artf/grapesjs
Live demo: https://grapesjs.com/demo.html

You can borrow some functions from there.
For example. The following functionality is missing in VisBug, which is in grapejs:

1. Layers (panels)
2. Style manager (panels)
3. Export/import code (zip archive + popup style and js live editor)
4. Live responsive mode (PC, Tablet, Mobile)
5. turn on/off the border grid of all elements

Think its. This is a very cool features.

**Comment by argyleink** [comment]
thanks for the tips, links and feature requests 👍
