### ISSUE TITLE
Test for Align Tool are failing on Mac

### ISSUE THREAD

**Issue by lavyda** [GoogleChromeLabs/ProjectVisBug#408]
Running tests for Align Tool on Mac causes these tests to fail:
* Can adjust column order
* Can adjust row order
* Can adjust row order

How to reproduce:
Run [tests](https://github.com/GoogleChromeLabs/ProjectVisBug/blob/master/app/features/flex.test.js) for Align Tool

Expected behaviour:
All tests should pass.

Fix:
Use [helper method](https://github.com/GoogleChromeLabs/ProjectVisBug/blob/master/tests/helpers.js#L22) to determine ctrl/cmd key.

**Comment by adhrinae** [comment]
I'm working on the other issue and the tests are failing because of this issue.
but I found this cannot be resolved easily.
It seems like `Meta + any key` doesn't work well in macOS well.

https://github.com/GoogleChrome/puppeteer/issues/1313

**Comment by lavyda** [comment]
It's weird because when I run tests (#409) on my Mac they pass.

**Comment by argyleink** [comment]
are these still failing after https://github.com/GoogleChromeLabs/ProjectVisBug/pull/409 merged?

**Comment by lavyda** [comment]
I think #409 hasn't been merged yet

**Comment by argyleink** [comment]
now it's merged!

**Comment by lavyda** [comment]
great! for me all tests pass

**Comment by argyleink** [comment]
cool! feel comfy closing this issue?

**Comment by adhrinae** [comment]
Yes. You can close this issue. 👍 Sorry for taking time to check this out.

**Comment by argyleink** [comment]
no prob! happy there's folks helpin 👍
