### ISSUE TITLE
Search autocomplete items should describe what they do

### ISSUE THREAD

**Issue by argyleink** [GoogleChromeLabs/ProjectVisBug#459]
![image](https://user-images.githubusercontent.com/1134620/85756092-5d650180-b6c3-11ea-80be-588b000caabd.png)

we can make those say something more than "plugin" and we should. work will be done here and in plugins https://github.com/GoogleChromeLabs/ProjectVisBug/blob/main/app/features/search.js#L12

**Comment by hchiam** [comment]
Sounds pretty straightforward. I'll take a look into this.
