### ISSUE TITLE
Ability to see Font-Family on info - Feature Request

### ISSUE THREAD

**Issue by JDBem** [GoogleChromeLabs/ProjectVisBug#472]
Not sure this has been requested yet, I've searched around but couldn't find any requests.

I use an extension called WhatFont which basically tells me the font family and a few other properties when I click on a text. 

I think adding that info to the Inspect button and info would be beneficial, it already has all other text properties showing so why not have the font-family as well. 

WhatFont Screenshot
<img width="300" alt="Screenshot 2020-11-11 at 12 44 38" src="https://user-images.githubusercontent.com/74302008/98813164-ab349900-241b-11eb-8759-f8ffcdf05e74.png">

**Comment by argyleink** [comment]
wow, thank you for reporting, as VisBug should be showing font families, especially since it's showing everything else (weight, line-height, size, etc). What a sneaky regression! I'll work on this soon!

**Comment by argyleink** [comment]
will be in the next version 0.3.4 which I'll release in the next day or 2 👍
