### ISSUE TITLE
Quit and open safari extensions preferences button is not working.

### ISSUE THREAD

**Issue by gnasamx** [GoogleChromeLabs/ProjectVisBug#473]
Hello

First of all  huge thanks for the safari extension.

I downloaded this extension, But nothing is happing when I clicked on 'Quit and open safari preferences'. I have uninstalled, shut down, reinstalled. I checked the extension tab from preference but Visbug is not listed in my extensions sidebar list. Any help?

Mac os version: 10.15.5
Safari version: 13.1.1

**Comment by argyleink** [comment]
Thank you so much for listing your Safari version, as Safari 14 is required to use their new extensions! I bet once you update Safari to 14, things will start to work. Let me know!

**Comment by argyleink** [comment]
I super appreciate your persistence and kind words too 🙂 👍

**Comment by gnasamx** [comment]
Ohh, I thought the same...version issue. But any way thanks for the reply.
