### ISSUE TITLE
hover card drags an image of the page around with it

### ISSUE THREAD

**Issue by smlombardi** [GoogleChromeLabs/ProjectVisBug#477]
When using any tool with an inspector popup, a rectangular image of the page below is cut out and moved around with it.  This is annoying and make is hard to view details below the inspector the way they actually look.
![SendPro® Online-20201123_090054](https://user-images.githubusercontent.com/835148/99971160-cfbd3900-2d6a-11eb-863b-81b9c3f7d41b.png)

This is using Edge Version 88.0.702.0 (Official build) Dev (64-bit), Mac Catalina, Visbug 0.2.39 for Edge.  It also happens with the Chrome Webstore version Extension installed instead.

**Comment by argyleink** [comment]
This is an issue with Chromium and has been fixed. Once the code hits your build, the issue will be gone 👍 

Read more here in the bug https://bugs.chromium.org/p/chromium/issues/detail?id=1147894#c1
