### ISSUE TITLE
A11y metatip style updates

### ISSUE THREAD

**Issue by argyleink** [GoogleChromeLabs/ProjectVisBug#496]
![Screen Shot 2021-02-05 at 7 45 21 AM](https://user-images.githubusercontent.com/1134620/107076899-f6531380-67a0-11eb-9c6e-60a2adf77725.png)

presentation is so nice, it's from https://superhighfives.com/pika. Can't do the color picker feature (would be awesome tho), but the larger swatches is so nice. much more inviting to copy and paste also, clicking the swatches should put it in the clipboard 👍🏻

**Comment by hchiam** [comment]
First time here! :D I'll take dibs on working on this for now. VisBug is awesome.

**Comment by argyleink** [comment]
> First time here! :D I'll take dibs on working on this for now. VisBug is awesome.

Thanks hchiam! Stoked to have you contributing 🙂
