### ISSUE TITLE
Wiki Sandbox url

### ISSUE THREAD

**Issue by PrinceRajRoy** [GoogleChromeLabs/ProjectVisBug#512]
For some reason the 

[The Sandbox: Try before you buy](https://visbug.page.link/sandbox) 

in wiki isn't working, could be an issue on Firebase side

![firebase](https://user-images.githubusercontent.com/47452572/120001795-c6e74180-bff1-11eb-8f20-54b4af58a5a9.PNG)

**Comment by argyleink** [comment]
nice find thanks! i havent looked at those firebase short links in a while, i bet they're inactive. i've updated the wiki 👍🏻
