### ISSUE TITLE
Crashes on Firefox Developer Edition with error: TypeError: can't access property "setAttribute", a is undefined

### ISSUE THREAD

**Issue by PsyGik** [GoogleChromeLabs/ProjectVisBug#529]
![image](https://user-images.githubusercontent.com/5432911/123612073-da1f4400-d81f-11eb-9ba0-339f4bf22d18.png)

Not sure if VisBug is supposed to trigger the React dev more error boundary.

**Comment by PsyGik** [comment]
works fine on Edge and Chrome, on the same local dev site

**Comment by argyleink** [comment]
interesting! do you have a url I can go try reproducing the error on? i've got FF dev edition and would love to set some breakpoints to see why a is undefined. from the error log there, looks like all you're doing in launching visbug and hovering around? does it repro in FF stable too?

**Comment by PsyGik** [comment]
![sample ig](https://user-images.githubusercontent.com/5432911/123683263-a49f4880-d869-11eb-8ace-4cb5d6894ccb.gif)

The error shows up on any site, keep the console open. (👆🏽 StackOverflow Homepage)

On dev mode, (at least on react projects), the error triggers the React Error boundary. 

More details: 

* FF Dev Edition: 90.0b12 (64-bit)
* Extension version: 0.3.21

The error happens at:

```js
class Ve extends HTMLElement {
  constructor() {
    super (),
    this.$shadow = this.attachShadow({
      mode: 'closed'
    })
  }
  connectedCallback() {
    this.$shadow.adoptedStyleSheets = [
      P
    ]
  }
  disconnectedCallback() {
  }
  set position(e) {
    this.$shadow.innerHTML = this.render(e)
  }
  set update({
    width: e,
    height: t,
    top: n,
    left: o
  }) {
    const {
      winHeight: r,
      winWidth: i
    }
    = Be(),
    [
      s
    ] = this.$shadow.children,
    [
      a,
      l,
      c,
      d,
      h
    ] = s.children;
    this.$shadow.host.style.display = 'block',
    s.setAttribute('viewBox', `0 0 ${ i } ${ r }`),
    a.setAttribute('width', e + 'px'), 🐛
    a.setAttribute('x', o),
    a.setAttribute('y', n),
    l.setAttribute('x1', o),
    l.setAttribute('x2', o),
    c.setAttribute('x1', o + e),
    c.setAttribute('x2', o + e),
    d.setAttribute('y1', n + window.scrollY),
    d.setAttribute('y2', n + window.scrollY),
    d.setAttribute('x2', i),
    h.setAttribute('y1', n + window.scrollY + t),
    h.setAttribute('y2', n + window.scrollY + t),
    h.setAttribute('x2', i)
  }
  render({
    x: e,
    y: t,
    width: n,
    height: o,
    top: r,
    left: i
  }) {
    const {
      winWidth: s,
      winHeight: a
    }
    = Be(),
    {
      offsetHeight: l
    }
    = document.body,
    c = t + window.scrollY;
    return `
      <svg
        width="100%"
        viewBox="0 0 ${ s } ${ a }"
        version="1.1" xmlns="http://www.w3.org/2000/svg"
      >
        <rect
          fill="none"
          width="${ n }" height="${ o }"
          x="${ e }" y="${ t }"
          style="display:none;"
        ></rect>
        <line x1="${ e }" y1="0" x2="${ e }" y2="${ l }"></line>
        <line x1="${ e + n }" y1="0" x2="${ e + n }" y2="${ l }"></line>
        <line x1="0" y1="${ c }" x2="${ s }" y2="${ c }"></line>
        <line x1="0" y1="${ c + o }" x2="${ s }" y2="${ c + o }"></line>
      </svg>
    `
  }
}
customElements.define('visbug-gridlines', Ve);
```

**Comment by PsyGik** [comment]
![image](https://user-images.githubusercontent.com/5432911/123684109-b2a19900-d86a-11eb-964e-dcb69badb2c9.png)
 
Happens on FF Stable as well.

**Comment by argyleink** [comment]
i see it, i got it. the bug is from destructuring children and assuming there's a certain node at an index, and the node is different in firefox because there's no constructible stylesheets. maybe if i can get the stylesheets to append instead of prepend, the bug will go away. or i can query the children instead of destructure them (the much safer route). 

thanks for the report! it looks like it's the dashed guides that are struggling to update due to this bug. i'm on it!

**Comment by argyleink** [comment]
![Screen Shot 2021-06-28 at 1 50 08 PM](https://user-images.githubusercontent.com/1134620/123702250-c243c200-d817-11eb-8ec4-7517555dba92.png)

will be live in FF soon! 👍🏻  ty for the bug report

**Comment by PsyGik** [comment]
Updated to the latest version. No more errors. Thanks for the quick fix!
