### ISSUE TITLE
New plugin: performance diagnostic snippet

### ISSUE THREAD

**Issue by argyleink** [GoogleChromeLabs/ProjectVisBug#538]
"diagnostic CSS snippet that exposes potential performance issues in your page’s <head> tags"

https://csswizardry.com/ct/

**Comment by hchiam** [comment]
Interesting!

**Comment by hchiam** [comment]
Quick reference from the [conference talk, slide 103](https://speakerdeck.com/csswizardry/get-your-head-straight?slide=103): 
```js
(() => {
  const ct = document.createElement("link");
  ct.rel = "stylesheet";
  ct.href = "https://csswizardry.com/ct/ct.css";
  ct.classList.add("ct");
  document.head.appendChild(ct);
})();
```
