### ISSUE TITLE
Copying from color picker does not work

### ISSUE THREAD

**Issue by katsar0v** [GoogleChromeLabs/ProjectVisBug#547]
![image](https://user-images.githubusercontent.com/7236157/152026099-8330422d-b524-4c88-b3de-6b3001e054cc.png)

I am trying to copy the hex value, but it is not working, anyone seeing this issue as well?

**Comment by argyleink** [comment]
it's a known [chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1066509)..
