### ISSUE TITLE
Color picker does not work

### ISSUE THREAD

**Issue by katsar0v** [GoogleChromeLabs/ProjectVisBug#548]
![image](https://user-images.githubusercontent.com/7236157/152026532-73ab9c5e-e3ce-4db2-acb3-b62d6b4ca6f6.png)

Does not seem to work as well and I get only `NaN`. Anyone else able to reproduce?

**Comment by argyleink** [comment]
another known [chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1275572)..
