### ISSUE TITLE
Undo Changes Made With VisBug

### ISSUE THREAD

**Issue by vadimvozmitsel** [GoogleChromeLabs/ProjectVisBug#559]
I urgently need help as I need to undo the changes that I accidentally made with VisBug. Linked below is a video that shows the problem.

I installed VisBug in Chrome and played around with it in my BubbleIO project. As you can see in the video, now my page automatically is resizing my top nav bar and my side nav bar to the right and to the bottom, past the viewport height and width. I can see that the Flexbox is being adjusted and manipulated in the Console but I don't know how to undo this behavior. 

In order to see the behavior on the page itself, here is the link: https://launchhaus.co/version-test/token-stream 

Reproduction video: https://share.cleanshot.com/qOoVvM

**Comment by argyleink** [comment]
a couple thoughts!
1. visbug doesnt do anything permanent to a page, you've reloaded and the problem persists?
2. did you by chance try the resize plugin that tests your site's fluidity?

**Comment by vadimvozmitsel** [comment]
Hello Adam!

Thank you for the quick response, I appreciate it.

Yes, I have reloaded the page many times, both inside my dev environment in the Bubble project and on the front end preview in Chrome, but the behavior continues to persist: when I shrink down the page to 960 and below, the flexbox begins to adjust back and forth as seen in the video.

And I’m not sure about the resize plugin to be honest, do you mean the flex control that is in the controls strip of VidBug chrome extension?

Best,

Vadim Vozmitsel
415.412.9611
***@***.***

**Comment by vadimvozmitsel** [comment]
Ah, thank you so much! That was it, I went through a bunch of the elements and indeed, I’m using a CSS plugin that slowly rotates elements and that was extending past the boundaries.

Appreciate your help. I will be spending more time with VisBug to figure out how to best incorporate it into my workflow, seems like a very powerful tool, I just wasn’t sure how to really go about using it since I am already in a visual editor inside Bubble.

Best,

Vadim Vozmitsel
415.412.9611
***@***.***

**Comment by argyleink** [comment]
have fun hackin! glad i was helpful
