### ISSUE TITLE
Where is Firefox add-on

### ISSUE THREAD

**Issue by filipw01** [GoogleChromeLabs/ProjectVisBug#565]
What happened to the Firefox add-on? Is it no longer supported or is that temporary?
<img width="1409" alt="Screenshot 2022-08-18 at 22 59 30" src="https://user-images.githubusercontent.com/22986859/185493751-9a949991-b3fd-4c75-ab5c-f3890299e401.png">
 https://addons.mozilla.org/en-US/firefox/addon/visbug/

**Comment by argyleink** [comment]
been submitted, waiting to hear back 👍🏻

**Comment by argyleink** [comment]
we've gone back and forth a few times, I think I've made all the changes they requested in today's upload 🙏🏻

**Comment by Falter-Sky** [comment]
@argyleink hey was just wondering about the upload time if its almost done 🙏🏻

**Comment by argyleink** [comment]
We've gone back and forth lots of times.. I've been waiting a week since the last interaction with the reviewer.. so sorry y'all!

**Comment by Falter-Sky** [comment]
no problem take your time i was just asking

**Comment by felipehw** [comment]
@argyleink 

Could you guys put the Firefox extension file to download directly from a third-party site?
In this way, we could use the Firefox extension without being vulnerable to the humor of Mozilla maintainers.

Ah, awesome extension, thanks for the job!

**Comment by argyleink** [comment]
that's a great idea! i've captured it in a new issue here https://github.com/GoogleChromeLabs/ProjectVisBug/issues/574

**Comment by SoyDiego** [comment]
Great extension, please, upload to third-party site.
Thanks for your work @argyleink

**Comment by argyleink** [comment]
resubmitted again

**Comment by SoyDiego** [comment]
Thanks @ argyleink I continue waiting to try in firefox :)

**Comment by dalemoore** [comment]
Really hope Mozilla approves this. I just found out about it and tested it in Chrome and it's great, but I prefer Firefox.

**Comment by argyleink** [comment]
they didnt, they rejected it because it had a bundled file in it... a bundled file in just the source.. the rest of it is all good, they just "dont like" that the file is there so they reject it. lemme try again. they're being super wierd.

**Comment by argyleink** [comment]
been 6 days since my last submission..

**Comment by arsh999cg** [comment]
@argyleink How to compile the source code manually for firefox? Can you provide tutorial please?

**Comment by argyleink** [comment]
there's some here https://github.com/GoogleChromeLabs/ProjectVisBug/wiki/Local-Extension-Dev-Testing-(DevBug)

the change you'll want to make is using the command `npm run extension:firefox` and make sure you have `web-ext` installed 👍🏻

**Comment by argyleink** [comment]
still back and forth with them, just made another submission

**Comment by argyleink** [comment]
Should be back!!
