### ISSUE TITLE
simulate translated text size expansion?

### ISSUE THREAD

**Issue by hchiam** [GoogleChromeLabs/ProjectVisBug#583]
When text gets translated from English to European languages, the text tends to get longer, and can cause layout bugs, especially if the layout wasn't initially designed with i18n in mind. The expansion isn't linear and is typically worse for shorter English texts ([here's the reference expansion size table](https://www.w3.org/International/articles/article-text-size#:~:text=in%20English%20source-,Average%20expansion,-Up%20to%2010)). It'd be nice if VisBug could also simulate this effect on layout. 

How about we add the ability to simulate translated text size by adding characters? Here's a script that lets you toggle the extra characters on/off (hit <kbd>Ctrl</kbd> to toggle), as well as choose whether to include spaces randomly sprinkled in to simulate text wrap (hit <kbd>p</kbd> to toggle): 

[translation-text-size-expansion-simulator.js](https://github.com/hchiam/learning-js/blob/main/bookmarklets/translation-text-size-expansion-simulator.js#L1)

And if you want to re-run the script by simply clicking on a bookmark, here's a [bookmarklet](https://en.wikipedia.org/wiki/Bookmarklet) version of that code: 

[translation-text-size-expansion-simulator.md](https://github.com/hchiam/learning-js/blob/main/bookmarklets/translation-text-size-expansion-simulator.md#hover-over-the-code-to-see-the-copy-to-clipboard-button)

## Demo: 
https://drive.google.com/file/d/1k1ono_vgUAgwJu3IiAHhhlUfn6IAOgF_/view?usp=sharing

**Comment by argyleink** [comment]
oh interesting, this is in the "chaos plugin" category to me, where VisBug can help simulate real world chaos so you can test and harden you UI design! i've been testing similarly except I use Google Translate to actually test different languages.

i could see this being a plugin tho yeah, make it a swift task to add some text noise: `/text-expand` or something.

**Comment by hchiam** [comment]
> oh interesting, this is in the "chaos plugin" category to me, where VisBug can help simulate real world chaos so you can test and harden you UI design! i've been testing similarly except I use Google Translate to actually test different languages.
> 
> i could see this being a plugin tho yeah, make it a swift task to add some text noise: `/text-expand` or something.

true, i can see how actual translation is better than simulated translation, especially if you know what languages you're targetting, and other situations devs might find themselves in. in other cases, this plugin might come in handy as a quick test and to conservatively estimate wider translation size expansions.

thanks! i'll set up the plugin later
