### ISSUE TITLE
Possible typo in metatip.element.js

### ISSUE THREAD

**Issue by nberlette** [GoogleChromeLabs/ProjectVisBug#596]
Referencing the file ./app/components/metatip/metatip.element.js, is that double quote in the `<span>` tag on L84 intentional?

https://github.com/GoogleChromeLabs/ProjectVisBug/blob/ed40795a3d165fbccd20ba5323cd20bfc5d67a62/app/components/metatip/metatip.element.js#LL84C18-L84C19

**Comment by argyleink** [comment]
it's not intentional, thx for reporting and thx to HTML for being forgiving 🙂

**Comment by argyleink** [comment]
did you wanna pr the fix, get the cred?

**Comment by argyleink** [comment]
well that wasnt you.. but if you do want to contribute I'm sure we can find somewhere else 😅
