### ISSUE TITLE
Comments: put notes on elements before screenshotting

### ISSUE THREAD

**Issue by argyleink** [GoogleChromeLabs/ProjectVisBug#62]
could be a whole new sidebar feature or optional addition to metatips

**Comment by davidyaha** [comment]
![image](https://user-images.githubusercontent.com/2580920/50382331-9030d280-06a5-11e9-93f4-0e1077b9665c.png)
Would love to see "zeplin-like" comments/notes on VisBug! 
Will be the first step toward team collaboration on live sites IMO.
The full user flow I'm suggesting:
1. Go to your wanted site.
2. Activate VisBug.
3. Write comments.
4. Open a "team workspace" on the wanted site.
5. Invite team members to reply and see the comments.
6. Make visual suggestion?

**Comment by argyleink** [comment]
looks like it can all be done with this https://www.usebubbles.com/

a whole separate extension devoted to making this a great experience 👍🏻
