### ISSUE TITLE
🐛 Unable to turn off VisBug

### ISSUE THREAD

**Issue by lucas-teks** [GoogleChromeLabs/ProjectVisBug#628]
👋  Hello,

I just downloaded VisBug on Chrome 125.0, Windows 11.

This [comment](https://github.com/GoogleChromeLabs/ProjectVisBug/issues/356) says `Alt + Shift + D` should toggle activation, however this only toggles the sidebar of VisBug.
Clicking on the extension icon or on the page (`RMB > VisBug > Show/Hide`) produce the same issue, forcing to refresh the page. Changing the shortcut didn't help.

It seems to be a  bug as the expected behavior is alright with the Firefox extension.
&nbsp;
<div align="center">
  <img src="https://github.com/GoogleChromeLabs/ProjectVisBug/assets/31036493/ccc9ca76-2c3a-43a3-b7b3-0a0cc43b7b9a" alt="description of the issue" width="350" />
  <p><em>The sidebar is hidden, but the extension is still active</em></p>
</div>
<p>&nbsp;</p>
Thank you, and great tool btw!

**Comment by argyleink** [comment]
watch out for `v0.4.5` which will have a fix for this later today!
thanks for sharing this regression 👍🏻
