### ISSUE TITLE
Linux system-ui missing, needs sans-serif backuip

### ISSUE THREAD

**Issue by argyleink** [GoogleChromeLabs/ProjectVisBug#630]
![Screenshot 2024-06-14 7 59 05 AM](https://github.com/GoogleChromeLabs/ProjectVisBug/assets/1134620/ad853959-b49a-46ad-b9ae-3c031937f2b8)
![Screenshot 2024-06-14 7 58 55 AM](https://github.com/GoogleChromeLabs/ProjectVisBug/assets/1134620/647887b9-1730-4241-b5c3-9d9e8d122b15)

find all [instances](https://github.com/GoogleChromeLabs/ProjectVisBug/blob/main/app/components/metatip/metatip.element.css#L40) and fix

**Comment by hchiam** [comment]
based on [searching `sans-serif` in this repo](https://github.com/search?q=repo%3AGoogleChromeLabs%2FProjectVisBug%20system-ui&type=code),
it looks like there are currently 6 instances of system-ui in 5 files (non-demo), and of those, the label element has a sans-serif fallback: 
[`font-family: system-ui, -apple-system, Segoe UI, Roboto, Ubuntu, Cantarell, Noto Sans, sans-serif;`](https://github.com/GoogleChromeLabs/ProjectVisBug/blob/939e85a4b6f15ee6775b488e3a12cf6464010fd9/app/components/selection/label.element.css#L30)

i could whip up a pr to get things started, but will need someone else to confirm how it looks
