### ISSUE TITLE
~[not bug]: Issue with the inspecting feature in the development version of the extension~

### ISSUE THREAD

**Issue by JabSYsEmb** [GoogleChromeLabs/ProjectVisBug#635]
Moving the mouse over elements creates a new <figure> each time instead of moving and updating the already displayed element. I had the problem when I tried to build the project locally and add it to the browser in both firefox and chrome. 

https://github.com/user-attachments/assets/027cbcf2-c37a-4eb2-9fb7-eecbbcf37451

**Comment by JabSYsEmb** [comment]
sorry my mistake.

**Comment by RubyRedThomas** [comment]
Unsuscribe

Sandra Lackland Thomas
