### ISSUE TITLE
Problem with the selection of elements whose classes contain special characters

### ISSUE THREAD

**Issue by JabSYsEmb** [GoogleChromeLabs/ProjectVisBug#636]
The `on_expand_selection` callback function almost doesn't work for websites styled by tailwind as special characters need to escaped by double backslash to be selectable, for instance `bg-[green]` needs to be queried as `bg-\\[green\\]` otherwise the `querySelector()` will throw an Error. 

![Recording 2024-07-14 at 18 22 52](https://github.com/user-attachments/assets/6328d66a-a13d-4f71-ac19-5146b47cc888)

**Comment by argyleink** [comment]
fixed in `v0.4.7` 🎉
