### ISSUE TITLE
Reuse Icons in other Application

### ISSUE THREAD

**Issue by jogibear9988** [GoogleChromeLabs/ProjectVisBug#642]
I'm workin on a designer webcomponent (https://node-projects.github.io/web-component-designer-demo/index.html), and like your different Tools, with different Keyboard Bindings. I'd like to do this the same in my designer.

For this I wanted to know, am I allowed to use your Icons from your Tools Box in my designer component?

**Comment by argyleink** [comment]
yep! you're welcome to use the same icons 🙂
