### ISSUE TITLE
Color mode settings

### ISSUE THREAD

**Issue by argyleink** [GoogleChromeLabs/ProjectVisBug#70]
where should the settings be?
- visbug html extension flyout thingy?
- custom ui and new button added to toolbar?

**Comment by rehat101** [comment]
I found a library that dev tools used to implement: https://bgrins.github.io/spectrum/ - Perhaps we can customize it to make it fit with VisBug's UI

**Comment by argyleink** [comment]
i was thinking last night that persisting user settings is blocking a lot of fun innovation right now, and a way to unblock all this work is to put these settings behind a number key. what do you think of something like this:

All number keys equal a setting to toggle:
[1] tool visibility
[2] dark/light
[3] toolbar side
etc?

the UX would then be, launch visbug on page, hit a key or 2 to get it into the right settings/state that you want, then go to town. 

it'd let us start playing with these custom settings, see how valuable they are, and determine whether or not we want them to persist. let's us discover how much we need settings vs assuming we need it and going and building infrastructure to support it. 

thoughts?

**Comment by dgeare** [comment]
@argyleink I think that's a pretty good intermediate solution. Especially for checking assumptions. 

Only concern/thought I had was be "is it possible that would get in the way of more a desirable future functionality, e.g. an alternate use case for those keys, and/or is there a good story for reclaiming them." I don't know that there is, that was just what came to mind as a thing to ponder. Other than that, seems like a great idea.

**Comment by argyleink** [comment]
figured out a swift way to take care of this, i'd really like folks to be able to choose their color type, and i've got a pr to do it via the context menu and an icon right click handler
