### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by argyleink** [GoogleChromeLabs/ProjectVisBug#87]
integration of this repo and running the tasks is straightforward for me, but i'm not sure how to upload a new zip to devtools via an api. would be nice to have master branch protected, accept PRs only, and each accepted PR is pretested and when accepted pushed to chrome web store

**Comment by DanielRuf** [comment]
Bump. Do you need any support?

**Comment by argyleink** [comment]
i had some when this repo was owned by me, but looks like the google cloud build integration was lost in the transfer. let me restore it, then we can go from there. 

i would love help with:
- [ ] on master merge kick off build that then deploys a zip to the chrome web store
- [ ] automate bumping the manifest
- [ ] automate uploading the zip
- [ ] on new PR run build, verify compile
- [ ] on new PR run `npm test`, see #86

**Comment by argyleink** [comment]
CI is done, tests are running, package.json commands are pretty much ready for automation. @DanielRuf  I'd love some help pushing builds to the chrome web store (i've done 0 research so far). I've got the version of visbug auto bumping on new builds if you use the `npm run extension:release` command, but it doesnt bump the extension manifest (see todo above). 

So I'm at the CD part now of the flow. Near the end 👍

**Comment by argyleink** [comment]
started an Action today that's got most the work laid down, need to update 2 things:
- manifest.json needs to sync with bumped package.json version (custom bash task?)
- would be best if the github action could access the new bumped version so it can access the versioned build file for upload, otherwise i'll need to update build tasks to create a static build zip for upload

file are built, task are running, need a few minor things customized and then this should be good to go

might be nice to publish a github release as well? but maybe that's for a later task?

**Comment by argyleink** [comment]
got it
